### ISSUE TITLE
qgsAffine  appears under Layer menu

### ISSUE THREAD

**Issue by geodrinx** [gingerik/qgsAffine#6]
qgsAffine   plugin   appears under  "Layer"  menu, instead of  "Vector".

I have an italian version of   2.8.1-Wien,  but I tested also setting in English US language, and nothing changes.    Plugin version is 1.0.1

Moreover, switching off and on the plugin, it appears duplicated (or more) in (Layer) menu.

**Comment by gingerik** [comment]
Thanks for reporting this @geodrinx.
I have already fixed the issues and will make a new release soon.
By the way, the plugin should currently be shown both within the Layer and the Vector menu.
